### ISSUE TITLE
Error on filtering subnets if there is no routing association

### ISSUE THREAD

**Issue by snovikov** [Flaconi/terraform-aws-transit-gateway-satellite#20]
Affected version: `v2.3.0` and earlier.

In case if there is a subnet among subnets filterded by `private_subnet_filters` which is not associated with any routing table, then you see error on `terraform plan`.

```
│ Error: query returned no results. Please change your search criteria and try again
│ 
│   with module.tgw-satellite.data.aws_route_table.this[6],
│   on .terraform/modules/tgw-satellite/data.tf line 38, in data "aws_route_table" "this":
│   38: data "aws_route_table" "this" {
```

This happens due to fact, that in this case subnet will be asssociated with default routing table of VPC, but no routing association is listed.

**Comment by danvaida** [comment]
To avoid confusion, I believe you're referring to the so-called "Main" routing table of a VPC.
We could use a data source that gathers information about the subnets and their (un)associated routing tables and then in a local variable, we could filter out such cases.
